/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.hiroshiba.voicevoxcore;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.File;
import org.junit.jupiter.api.Test;

class MetaTest {
  @Test
  void checkLoad() {
    // cwdはvoicevox_core/crates/voicevox_core_java_api/lib
    String cwd = System.getProperty("user.dir");
    File path = new File(cwd + "/../../test_util/data/model/sample.vvm");
    try (VoiceModelFile model = new VoiceModelFile(path.getAbsolutePath())) {
      assertNotNull(model.metas);
    }
  }
}
