/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.Hiroshiba.VoicevoxCore;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OpenJtalkTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertTrue(OpenJtalk.test(), "someLibraryMethod should return 'true'");
  }
}
