# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default]
extend-ignore-identifiers-re = [
    "\\bPNGs\\b", # https://github.com/crate-ci/typos/issues/745
]
extend-ignore-words-re = [
    "^[A-Za-z]{2}$", # "ba"（crate-ci/typos#848, crate-ci/typos#413）、Python以外での"NDArray"など
]

[default.extend-identifiers]
NdArray="NdArray" # onnxruntime::session::NdArray

[default.extend-words]

[files]
extend-exclude = ["*.svg", "*.onnx"]
