name: Install cargo-deny
description: cargo-denyをインストールする。

runs:
  using: composite
  steps:
    - name: Install cargo-binstall
      uses: taiki-e/install-action@3f74d7c16a4242f1c95561e98edc25d36adb4375 # v2.87.12
      with:
        tool: cargo-binstall
    - name: Install cargo-deny
      shell: bash
      run: cargo binstall cargo-deny@^0.18 --no-confirm --log-level debug
