name: Install cargo-deny
description: cargo-denyをインストールする。

runs:
  using: composite
  steps:
    - name: Install cargo-binstall
      uses: taiki-e/install-action@cargo-binstall
    - name: Install cargo-deny
      shell: bash
      run: cargo binstall cargo-deny@^0.18 --no-confirm --log-level debug
