name: Create venv
description: Pythonの仮想環境を作成し、$PATHと$VIRTUAL_ENVを設定する。

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        virtual_env="$RUNNER_TEMP/.venv"
        python -m venv "$virtual_env"
        if [ "$RUNNER_OS" = Windows ]; then
          echo "$virtual_env/Scripts" >> "$GITHUB_PATH"
        else
          echo "$virtual_env/bin" >> "$GITHUB_PATH"
        fi
        echo "VIRTUAL_ENV=$virtual_env" >> "$GITHUB_ENV"
