[package]
edition = "2021"
name = "voicevox_core_node_api"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = "2"
napi-derive = "2"
voicevox_core.workspace = true

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
