/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Mora {
  /** 文字。 */
  text: string
  /** 子音の音素。 */
  consonant?: string
  /** 子音の音長。 */
  consonantLength?: number
  /** 母音の音素。 */
  vowel: string
  /** 母音の音長。 */
  vowelLength: number
  /** 音高。 */
  pitch: number
}
export interface AccentPhrase {
  /** モーラの配列。 */
  moras: Mora[]
  /** アクセント箇所。 */
  accent: number
  /** 後ろに無音を付けるかどうか。 */
  pauseMora?: Mora
  /** 疑問系かどうか。 */
  isInterrogative: boolean
}
export interface AudioQuery {
  /** アクセント句の配列。 */
  accentPhrases: AccentPhrase[]
  /** 全体の話速。 */
  speedScale: number
  /** 全体の音高。 */
  pitchScale: number
  /** 全体の抑揚。 */
  intonationScale: number
  /** 全体の音量。 */
  volumeScale: number
  /** 音声の前の無音時間。 */
  prePhonemeLength: number
  /** 音声の後の無音時間。 */
  postPhonemeLength: number
  /** 音声データの出力サンプリングレート。 */
  outputSamplingRate: number
  /** 音声データをステレオ出力するか否か。 */
  outputStereo: boolean
  /**
   * \[読み取り専用\] AquesTalk風記法。
   *
   * [`Synthesizer::audio_query`]が返すもののみ`Some`となる。入力としてのAudioQueryでは無視され
   * る。
   *
   * [`Synthesizer::audio_query`]: crate::Synthesizer::audio_query
   */
  kana?: string
}
export type JsSupportedDevices = SupportedDevices
export class SupportedDevices {
  static create(): JsSupportedDevices
  get cpu(): boolean
  get cuda(): boolean
  get dml(): boolean
  toJson(): any
}
