/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsSupportedDevices = SupportedDevices
export class SupportedDevices {
  static create(): JsSupportedDevices
  get cpu(): boolean
  get cuda(): boolean
  get dml(): boolean
}
