[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
cbindgen = "0.26.0"
clap.workspace = true
color-eyre = "0.6.2"
eyre = "0.6.8"
fs-err.workspace = true
