[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
cbindgen = "0.24.3"
clap = { version = "3.2.22", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
