[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
cbindgen = "0.24.3"
clap = { version = "4.0.10", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
