name: Upload a GitHub release asset
description: GitHubのリリースにアセットをアップロードする。

inputs:
  id:
    required: true
  file:
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        release_id=${{ inputs.id }}
        file=${{ inputs.file }}
        name=$(basename "$file")

        gh api \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$release_id/assets?name=$name" \
          --method POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          --input "$file"
