name: Upload a GitHub release asset
description: GitHubのリリースにアセットをアップロードする。

inputs:
  id:
    required: true
  file:
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        release_id=${{ inputs.id }}
        file='${{ inputs.file }}'
        name=$(basename "$file")
        curl \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$release_id/assets?name=$name" \
          -fL \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ github.token }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -H 'Content-Type: application/octet-stream' \
          --data-binary "@$file"
