name: upload artifact
description: artifactをzipでアップロードする
inputs:
  artifact_dir:
    description: 作業ディレクトリ
    required: true
  assert_name:
    description: artifactの名前
    required: true
  repo_token:
    description: github token
    required: true
  version:
    description: version
    required: true
runs:
  using: "composite"
  steps:
    - name: Archive artifact
      if: (!contains(inputs.assert_name,'windows'))
      shell: bash
      run: |
        cd "${{ inputs.artifact_dir }}"
        zip -r "../${{ inputs.assert_name }}.zip" "${{ inputs.assert_name }}"
    - name: Archive artifact (Windows)
      if: contains(inputs.assert_name, 'windows')
      shell: bash
      run: |
        powershell Compress-Archive -Path "${{ inputs.artifact_dir }}/${{ inputs.assert_name }}" -DestinationPath "${{ inputs.assert_name }}.zip"
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.repo_token }}
        prerelease: true
        tag: ${{ inputs.version }}
        file: ${{ inputs.assert_name }}.zip
