"""無料で使える中品質なテキスト読み上げソフトウェア、VOICEVOXのコア。"""

# TODO: `wav_from_s16le`を復活させる
# https://github.com/VOICEVOX/voicevox_core/issues/970

from ._python import (  # noqa: F401
    AccelerationMode,
    AccentPhrase,
    AudioQuery,
    CharacterMeta,
    CharacterVersion,
    Mora,
    StyleId,
    StyleMeta,
    StyleType,
    SupportedDevices,
    UserDictWord,
    UserDictWordType,
    VoiceModelId,
)
from ._rust import (  # noqa: F401
    AnalyzeTextError,
    GetSupportedDevicesError,
    GpuSupportError,
    InitInferenceRuntimeError,
    InvalidModelDataError,
    InvalidWordError,
    LoadUserDictError,
    ModelAlreadyLoadedError,
    ModelNotFoundError,
    NotLoadedOpenjtalkDictError,
    OpenZipFileError,
    ParseKanaError,
    ReadZipEntryError,
    RunModelError,
    SaveUserDictError,
    StyleAlreadyLoadedError,
    StyleNotFoundError,
    UseUserDictError,
    WordNotFoundError,
    __version__,
)

from . import asyncio, blocking  # noqa: F401 isort: skip

__all__ = [
    "__version__",
    "AccelerationMode",
    "AccentPhrase",
    "AnalyzeTextError",
    "AudioQuery",
    "asyncio",
    "blocking",
    "CharacterMeta",
    "CharacterVersion",
    "GetSupportedDevicesError",
    "GpuSupportError",
    "InitInferenceRuntimeError",
    "InvalidModelDataError",
    "InvalidWordError",
    "LoadUserDictError",
    "ModelAlreadyLoadedError",
    "ModelNotFoundError",
    "Mora",
    "NotLoadedOpenjtalkDictError",
    "OpenZipFileError",
    "ParseKanaError",
    "ReadZipEntryError",
    "RunModelError",
    "SaveUserDictError",
    "StyleAlreadyLoadedError",
    "StyleId",
    "StyleMeta",
    "StyleNotFoundError",
    "StyleType",
    "SupportedDevices",
    "UseUserDictError",
    "UserDictWord",
    "UserDictWordType",
    "VoiceModelId",
    "WordNotFoundError",
]
