"""無料で使える中品質なテキスト読み上げソフトウェア、VOICEVOXのコア。"""

from . import _load_dlls  # noqa: F401
from ._models import (  # noqa: F401
    AccelerationMode,
    AccentPhrase,
    AudioQuery,
    Mora,
    MorphableTargetInfo,
    PermittedSynthesisMorphing,
    SpeakerMeta,
    SpeakerSupportedFeatures,
    StyleId,
    StyleVersion,
    SupportedDevices,
    UserDictWord,
    UserDictWordType,
    VoiceModelId,
)
from ._rust import (  # noqa: F401
    ExtractFullContextLabelError,
    GetSupportedDevicesError,
    GpuSupportError,
    InferenceFailedError,
    InvalidModelDataError,
    InvalidWordError,
    LoadUserDictError,
    ModelAlreadyLoadedError,
    ModelNotFoundError,
    NotLoadedOpenjtalkDictError,
    OpenZipFileError,
    ParseKanaError,
    ReadZipEntryError,
    SaveUserDictError,
    StyleAlreadyLoadedError,
    StyleNotFoundError,
    UseUserDictError,
    WordNotFoundError,
    __version__,
    supported_devices,
)

from . import asyncio, blocking  # noqa: F401 isort: skip

__all__ = [
    "__version__",
    "AccelerationMode",
    "AccentPhrase",
    "AudioQuery",
    "asyncio",
    "blocking",
    "ExtractFullContextLabelError",
    "GetSupportedDevicesError",
    "GpuSupportError",
    "InferenceFailedError",
    "InvalidModelDataError",
    "InvalidWordError",
    "LoadUserDictError",
    "ModelAlreadyLoadedError",
    "ModelNotFoundError",
    "Mora",
    "MorphableTargetInfo",
    "NotLoadedOpenjtalkDictError",
    "OpenZipFileError",
    "ParseKanaError",
    "PermittedSynthesisMorphing",
    "ReadZipEntryError",
    "SaveUserDictError",
    "SpeakerMeta",
    "SpeakerSupportedFeatures",
    "StyleAlreadyLoadedError",
    "StyleId",
    "StyleNotFoundError",
    "StyleVersion",
    "SupportedDevices",
    "supported_devices",
    "UseUserDictError",
    "UserDictWord",
    "UserDictWordType",
    "VoiceModelId",
    "WordNotFoundError",
]
