name: Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .cargo/config.toml
      - .github/workflows/benchmarks.yml
      - Cargo.*
      - crates/voicevox_core/Cargo.toml
      - crates/voicevox_core/benches/simulation.rs
      - crates/voicevox_core/build.rs
      - crates/voicevox_core/src/**
      - crates/voicevox_core_build_features/Cargo.toml
      - crates/voicevox_core_build_features/onnxruntime-libs.toml
      - crates/voicevox_core_build_features/src/**
      - crates/voicevox_core_macros/Cargo.toml
      - crates/voicevox_core_macros/src/**
      - model/**
      - onnxruntime-version.txt
      - rust-toolchain
  workflow_dispatch:

jobs:
  rust-api:
    name: Rust API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          bins: cargo-codspeed
          cache-target: release
          inherit-toolchain: true

      - name: Set up test data
        run: cargo check -vp test_util

      - name: Build
        run: cargo codspeed build -p voicevox_core --bench simulation --features buildtime-download-onnxruntime,load-onnxruntime -m simulation

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@93bbfdc546455345ae00c6f4e100a37838b37bcf # v4.14.0
        with:
          run: cargo codspeed run
          mode: simulation
