name: Pinact

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/pinact.yaml
      - .github/actions/**
      - .github/workflows/*.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  pinact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Pinact
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
          min_age: "7"
