name: PSScriptAnalyzer
on:
  push:
    branches:
      - main
    paths:
      - '**.ps1'
      - '.github/workflows/psscriptanalyzer.yml'
defaults:
  run:
    shell: bash
jobs:
  psscriptanalyzer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          recurse: true
      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: psscriptanalyzer
