name: Python API Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/python-benchmarks.yml
      - Cargo.*
      - crates/voicevox_core/Cargo.toml
      - crates/voicevox_core/src/**
      - crates/voicevox_core_python_api/Cargo.toml
      - crates/voicevox_core_python_api/poetry.lock
      - crates/voicevox_core_python_api/pyproject.toml
      - crates/voicevox_core_python_api/python/benches/*.py
      - crates/voicevox_core_python_api/python/voicevox_core/**
      - crates/voicevox_core_python_api/src/**
  workflow_dispatch:

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          inherit-toolchain: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Set up Poetry
        working-directory: ./crates/voicevox_core_python_api
        run: |
          pip install --upgrade poetry
          poetry install --with dev --with test

      - name: Setup test data
        run: cargo check -vp test_util

      - name: Build
        working-directory: ./crates/voicevox_core_python_api
        run: poetry run maturin develop --locked --profile release -v

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: poetry run pytest ./python/benches/ --codspeed --codspeed-mode walltime
          mode: walltime
          working-directory: ./crates/voicevox_core_python_api
