name: Renovate

on:
  push:
    branches:
      - chore-use-renovate-for-all-deps
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          configurationFile: renovate.json5
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
