name: Rust API Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/rust-benchmarks.yml
      - Cargo.*
      - crates/voicevox_core/Cargo.toml
      - crates/voicevox_core/benches/*
      - crates/voicevox_core/src/**
  workflow_dispatch:

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-codspeed
          cache-target: release
          inherit-toolchain: true

      - name: Set up test data
        run: cargo check -vp test_util

      - name: Build
        run: cargo codspeed build -p voicevox_core --features load-onnxruntime -m walltime benches

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run -m walltime
          mode: walltime
        env:
          VOICEVOX_CORE_BENCH_CONFIG: |
            {
              "include-long-input-text": ${{ github.event_name != 'pull_request'  }}
            }
