name: shellcheck
on:
  push:
    branches: 
      - main
  pull_request:
    paths:
      - '**.sh'
      - '**.bash'
jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: ShellCheck
        run: git ls-files | grep -E '\.(ba)?sh' | xargs shellcheck
